Student slider viewtutorinfo css/js
STEM-E-Youth-Career-Development-Program/tutor-app pull request #11
Opened 2024-09-09 01:21 UTC by Amitganguly0327

2024-09-16 00:59 UTC, Matthew1177 requested changes
Please remove hardcoded info (despite current info fields being blank)

2024-09-16 00:59 UTC, Matthew1177 commented on src/pages/ViewTutorInfo.js
> +                <StudentsSlider studentIds={{ ...tutor.students, leFaNrKmmcXWjr6RvIPb: { subjectsTutored: "Geometry" } }} />
the student id shouldn't be hardcoded

2024-09-16 00:59 UTC, Matthew1177 commented on src/pages/ViewTutorInfo.js
> +            if (newStudentId === "leFaNrKmmcXWjr6RvIPb" || student.firstName !== "Student") {
same issue here

2024-09-16 00:59 UTC, Matthew1177 commented on src/pages/ViewTutorInfo.js
> +let hardCodedStudentData = {
no hardcoding!!!

2024-09-23 00:09 UTC, Amitganguly0327 commented
Okay! Sorry for leaving that in there. I have removed all hard coding in my latest commit

2024-10-07 07:14 UTC, Matthew1177 requested changes

2024-10-07 07:14 UTC, Matthew1177 commented on src/pages/ViewTutorInfo.js
> +import { firebaseApp } from "../firebaseApp";
you shouldn't be directly interacting with firebase, please use the slices in the state folder

2024-10-07 07:14 UTC, Matthew1177 commented on src/pages/ViewTutorInfo.js
> +import { firebaseApp } from "../firebaseApp";
you may need to rebase as the slices have been updated since this was opened

2025-02-10 02:23 UTC, merged